dataset: "IMDBMulti"

IGFM:
  model_name: 'IGFM'
  dataset_name: 'IMDBMulti'
  epochs: 10000
  use_val: True
  val_ratio: 0.25
  iter_val_start: 9000
  iter_val_every: 100
  save_best: True
  save_best_all: False
  multilabel: False
  patience: -1
  seed: 1111
  lr: 0.01             
  weight_decay: 0.000   
  lr_scheduler: False
  monitor: "mse"
  recache: False
  optimizer: "Adam"
  num_layers: 2
  activation: "relu"
  multirun: 1 
  gnn_encoder: "GIN"      
  multi_contrast: False
  gnn_filters: [128]
  dropout: 0.
  deepsets: True
  use_bn: False
  deepsets_inner_act: "relu"      
  deepsets_outer_act: "relu"
  fuse_type: "cat"       # 'add', 'stack', 'cat'
  pooling: 'add'     # 'add', 'mean'
  reduction: 2
  inner_mlp: True       # 'mlp'
  inner_mlp_layers: 1
  outer_mlp_layers: 1
  use_mlp_score: True
  mlp_score_layer: 2
  batch_size: 256
  val_batch_size: 512
  use_all_val: True
  val_size: 60000
  use_sim: True
  NTN_layers: 1
  tensor_neurons: 16
  output_comb: True  
  norm: True
  use_deepsets: True
  use_ff: True
  num_ff: 1
  sep: True
  measure: 'JSD'
  cl_loss_norm: True
  norm_type: 'tanh'  # sum, sigmoid, tanh

  clip_grad: False
  num_works: 10
  max_set_size: 89
  use_gs: True
  gs_weight: 0.5
  tau: 0.001
  n_sink_iter: 20
  n_samples: 1
  use_gs: True
  x_augment: True