dataset: "LINUX"

IGFM:
  model_name: 'IGFM'
  dataset_name: 'LINUX'
  epochs: 10000
  use_val: True
  val_ratio: 0.25
  iter_val_start: 9000
  iter_val_every: 10
  save_best: True
  save_best_all: False
  multilabel: False
  lr: 0.001              
  weight_decay: 0.000   
  lr_scheduler: False
  monitor: "mse"
  optimizer: "Adam"
  num_layers: 2
  activation: "relu"
  multirun: 1
  scale: 1
  show_last: False
  gnn_encoder: "GIN"      
  multi_contrast: False
  gnn_filters: [64, 16]
  dropout: 0.
  deepsets: True
  use_bn: False
  deepsets_inner_act: "relu"      
  deepsets_outer_act: "relu"
  fuse_type: "cat"       # 'add', 'stack', 'cat'
  pooling: 'add'         # 'add', 'mean'
  reduction: 2
  inner_mlp: True        # 'mlp'
  inner_mlp_layers: 1
  outer_mlp_layers: 1

  use_mlp_score: True
  mlp_score_layer: 2
  batch_size: 128
  val_batch_size: 512
  use_all_val: True
  val_size: 50000
  
  use_sim: True
  NTN_layers: 1
  tensor_neurons: 16
  output_comb: True  

  use_deepsets: False
  use_ff: False
  sep: False
  measure: 'JSD'

  clip_grad: True
  num_works: 10

  seed: 1234
  use_gs: False
  gs_weight: 0.5
  max_set_size: 10
  
  tau: 0.001
  n_sink_iter: 20
  n_samples: 1
  x_augment: False